### ISSUE TITLE
"No internet" leading to "Coingecko is unreachable: Exit the script"

### ISSUE THREAD

**Issue by snarflakes** [llvllch/btcticker#25] opened 2021-01-11 18:42 UTC
Despite updating, I keep getting INFO: No internet x 2, which then eventually reconnects, gets data from coingecko, and then on the next refresh hits "No internet" x 1,  then "getting data," and then at some point during getting data from coingecko leads to "Coingecko is unreachable - Exit the script."  
Problem: During times of weak wifi, or internet blips occuring during the coingecko data retrieval stage, coingecko data loss or interruption leads to shut down of program instead of reattempting.  This has been occuring once every 2 days.  
Solution: Do we need to add in another pause somewhere during the coingecko data grab? Or perhaps a Re-attempt if there was a disruption during coingecko download so the program doesn't shut down when hitting this challenge?

**Comment by llvllch** [comment] 2021-01-11 18:47
The current version should just wait 10 seconds and try again if the
coingecko pull fails. This should also happen if an exception is thrown mid
pull. I'll have another look at the code. I think my use of systemd might
be stopping me from seeing it.

**Comment by snarflakes** [comment] 2021-01-12 00:52
I will pull again, to retest in case I missed an update.

**Comment by llvllch** [comment] 2021-01-13 13:29
If connection drops, a holding screen should display until connection is
re-established. Let me know how you get on….

**Comment by snarflakes** [comment] 2021-01-15 05:45
Thanks,
The problem has changed since the last pull. I’m checking frequency pattern and to make sure it is repeating exactly the same errors. I will update in a few days.

**Comment by snarflakes** [comment] 2021-01-15 17:49
Okay this error repeated x2 now.  Re-occurring every 1-2 days. Since I pulled your last changes per my previous comment this is occurring.  The old problem which said Coingecko is unreachable - Exit the script doesn't seem to be occurring any more.

This is what is happening now:

I see one: INFO:root: No internet
it moves forward no issues and getting data
Then it goes 

DEBUG:root:spi end
DEBUG:root: close 5V, module enteres 0 power consumptions...
Trace back (most recent call last):
File "btc ticker.pay", line 316 n <module>
Main()
File "btc ticker.pay", line 271, in main
Key1state = GPIO.input(key1)
RuntimeError: please set pin numbering mode using GPIO.setmode(GPIO.BOARD or GPIO.setmode(GPIO.BCM)

The pi screen displays your little Axie, when this has happened. Screen still detached and accessible.

Is a reboot occurring? I haven't seen the error happen live, I just find the pi in this state.

**Comment by llvllch** [comment] 2021-01-15 17:57
what is File “btc ticker.pay”? Or is that just some typos that appears
during cut and paste. It looks like pressing key 4 is throwing that error,
I’ll try to reproduce.

**Comment by snarflakes** [comment] 2021-01-15 17:59
sorry autocorrect.  Should read .py

**Comment by llvllch** [comment] 2021-02-10 17:23
Closing for now. No news is good news :)

**Closed by llvllch** 2021-02-10 17:23 UTC

**Comment by SR00000** [comment] 2021-02-20 03:32
I wanted to comment on this because I had this problem earlier and found the issue. My internet gateway had "advanced security" enabled and it automatically blocked outgoing pings from my Pi because it thought it was trying to DDOS another network. You have to disable that advanced/smart security you may have enabled on your modem/gateway.

If you're able to use the command "curl -X GET https://api.coingecko.com/api/v3/exchanges" and get a screen full of text, that means its definitely been disabled from your modems end. Good luck!
